all: oppgave1 oppgave2 oppgave3 oppgave4 oppgave5

oppgave1:
	gcc -o oppgave1 oppgave1.c

oppgave2:
	gcc -o oppgave2 oppgave2.c

oppgave3:
	gcc -o oppgave3 oppgave3.c

oppgave4:
	gcc -o oppgave4 oppgave4.c

oppgave5:
	gcc -o oppgave5 oppgave5.c

clean:
	rm -f oppgave1 oppgave2 oppgave3 oppgave4 oppgave5